name: flutter_ar_ecommerce
description: A Flutter e-commerce app with 3D AR Models
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  model_viewer_plus: 1.7.2
  webview_flutter: ^4.8.0
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/table_wood.glb
    - assets/Meuble_ID_1.glb
    - assets/table_wood.webp
    - assets/Meuble_ID_1.webp
    - assets/LOGO Ar Design.png
    - assets/ar_icon.png
    - assets/price chop.png
    - assets/chop.png
    - assets/README.txt
    - assets/ 